name: learn_dart_together
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  http: ^1.2.1
  xml: ^6.5.0
  path: ^1.8.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.0
  json_serializable: ^6.7.1
