name: learn_dart_together
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  csv: ^6.0.0
  # path: ^1.8.0
  http: ^1.2.1
  xml: ^6.5.0
  calc: ^0.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
