name: dart_cli_practice
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
