name: learn_dart_together
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  csv: ^6.0.0
  http: ^1.2.1
  intl: ^0.19.0
  xml: ^6.5.0
  xml2json: ^6.2.3
  # path: ^1.8.0

dev_dependencies:
  collection: ^1.18.0
  lints: ^3.0.0
  test: ^1.24.0
